// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjTLfqGjfTVITRvCV4cb2JKMw97L1-boo',
    appId: '1:407457402667:web:57873d104ec38b88097f6e',
    messagingSenderId: '407457402667',
    projectId: 'flutterauth-7d04a',
    authDomain: 'flutterauth-7d04a.firebaseapp.com',
    storageBucket: 'flutterauth-7d04a.appspot.com',
    measurementId: 'G-DLHK5GYM66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9YCF4IOrB3HKtdpyIh7MrxnjTlb8raiE',
    appId: '1:407457402667:android:200eb1ed06237f70097f6e',
    messagingSenderId: '407457402667',
    projectId: 'flutterauth-7d04a',
    storageBucket: 'flutterauth-7d04a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArStpis3gK59cRPx6xQss_v0u_TZCHcQc',
    appId: '1:407457402667:ios:8e5fd136eeae2b12097f6e',
    messagingSenderId: '407457402667',
    projectId: 'flutterauth-7d04a',
    storageBucket: 'flutterauth-7d04a.appspot.com',
    iosBundleId: 'com.example.taskForFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArStpis3gK59cRPx6xQss_v0u_TZCHcQc',
    appId: '1:407457402667:ios:f74a7b3cb2a3b9ea097f6e',
    messagingSenderId: '407457402667',
    projectId: 'flutterauth-7d04a',
    storageBucket: 'flutterauth-7d04a.appspot.com',
    iosBundleId: 'com.example.taskForFlutter.RunnerTests',
  );
}
